# Generated by Django 5.1.15 on 2026-09-10 04:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('icon', models.CharField(default='bi-gear-wide-connected', help_text='Bootstrap Icon class', max_length=40)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=25)),
                ('shipping_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='United States', max_length=64)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid / Confirmed'), ('processing', 'Processing Warehouse Pick'), ('shipped', 'Shipped / In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='paid', max_length=20)),
                ('payment_method', models.CharField(default='Credit Card (Demo)', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='SKU / Part Number')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('brand', models.CharField(default='CarCraft OEM Performance', max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('specifications', models.TextField(blank=True, help_text='Fitment, material, dimensions, compatibility guide')),
                ('primary_image_url', models.URLField(blank=True, default='', help_text='High-res photo URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='parts/')),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='store.category')),
            ],
            options={
                'verbose_name': 'Part & Accessory',
                'verbose_name_plural': 'Parts & Accessories',
                'ordering': ['-featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=150)),
                ('part_sku', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='store.part')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
