# Generated by Django 5.1.15 on 2026-09-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='primary_image_url',
            field=models.URLField(blank=True, default='', help_text='High-res photo URL', max_length=500),
        ),
    ]
