# Generated by Django 5.1.15 on 2026-09-10 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Bay 1 - Dyno & Diagnostics', max_length=64, unique=True)),
                ('bay_number', models.PositiveSmallIntegerField(unique=True)),
                ('assigned_technician', models.CharField(help_text='Lead Technician / ASE Certified Specialist', max_length=100)),
                ('specialty', models.CharField(default='General Automotive Service', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Bay',
                'verbose_name_plural': 'Service Bays',
                'ordering': ['bay_number'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Customer Full Name')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('customer_phone', models.CharField(max_length=25, verbose_name='Phone Number')),
                ('vehicle_description', models.CharField(help_text='e.g. 2022 Porsche 911 GT3 / 2024 Ford F-150', max_length=150, verbose_name='Vehicle Year, Make & Model')),
                ('vehicle_vin', models.CharField(blank=True, max_length=17, verbose_name='VIN (Optional)')),
                ('vehicle_mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Current Mileage')),
                ('service_type', models.CharField(choices=[('oil_synthetic', 'Full Synthetic Oil & Filter Service ($129.00)'), ('brake_performance', 'Performance Brake Pad & Rotor Service ($389.00)'), ('tire_alignment', 'Tire Rotation, Laser Balancing & 4-Wheel Alignment ($149.00)'), ('diagnostics_full', 'Comprehensive OBD-II Computer & Electrical Diagnostics ($189.00)'), ('multi_point_inspection', '50-Point Certified Pre-Purchase / Safety Inspection ($99.00)'), ('transmission_flush', 'Transmission Flush & Drivetrain Fluid Service ($299.00)'), ('ev_battery_health', 'EV / Hybrid High-Voltage Battery Health & Cooling Diagnostic ($249.00)'), ('performance_tune', 'Custom ECU Stage-1 Calibration & Dyno Optimization ($599.00)')], default='oil_synthetic', max_length=40)),
                ('date', models.DateField(db_index=True)),
                ('time_slot', models.CharField(choices=[('08:00', '08:00 AM - 09:30 AM'), ('09:30', '09:30 AM - 11:00 AM'), ('11:00', '11:00 AM - 12:30 PM'), ('13:00', '01:00 PM - 02:30 PM'), ('14:30', '02:30 PM - 04:00 PM'), ('16:00', '04:00 PM - 05:30 PM')], db_index=True, default='08:00', max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress / On Lift'), ('completed', 'Completed / Ready for Pickup'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Customer Notes / Specific Concerns')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Technician Workshop Notes')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_bay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='service.servicebay')),
            ],
            options={
                'verbose_name': 'Service Appointment',
                'verbose_name_plural': 'Service Appointments',
                'ordering': ['date', 'time_slot', 'assigned_bay__bay_number'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('assigned_bay', 'date', 'time_slot'), name='unique_bay_booking_per_slot')],
            },
        ),
    ]
