# Generated by Django 5.1.15 on 2026-09-10 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_bay_booking_per_slot',
        ),
    ]
