# Generated by Django 5.1.15 on 2026-09-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_appointment_unique_bay_booking_per_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='vehicle_mileage',
        ),
        migrations.AddField(
            model_name='appointment',
            name='vehicle_odometer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Current Odometer (km)'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[('oil_synthetic', 'Full Synthetic Oil & Filter Service (₹4,500)'), ('brake_performance', 'Performance Brake Pad & Rotor Service (₹12,500)'), ('tire_alignment', 'Tire Rotation, Laser Balancing & 4-Wheel Alignment (₹3,200)'), ('diagnostics_full', 'Comprehensive OBD-II Computer & Electrical Diagnostics (₹2,800)'), ('multi_point_inspection', '50-Point Certified Pre-Purchase / Safety Inspection (₹2,500)'), ('transmission_flush', 'Transmission Flush & Drivetrain Fluid Service (₹8,900)'), ('ev_battery_health', 'EV / Hybrid High-Voltage Battery Health & Cooling Diagnostic (₹4,200)'), ('performance_tune', 'Custom ECU Stage-1 Calibration & Dyno Optimization (₹18,500)')], default='oil_synthetic', max_length=40),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vehicle_description',
            field=models.CharField(help_text='e.g. 2024 Mahindra XUV700 AX7L / 2024 Hyundai Ioniq 5', max_length=150, verbose_name='Vehicle Year, Make & Model'),
        ),
    ]
