# Generated by Django 5.1.15 on 2026-09-10 04:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=17, unique=True, verbose_name='VIN Number')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)])),
                ('make', models.CharField(db_index=True, max_length=64)),
                ('model', models.CharField(db_index=True, max_length=64)),
                ('trim', models.CharField(blank=True, help_text='e.g. GTS, Platinum, AMG Night Edition', max_length=64)),
                ('type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Truck', 'Truck'), ('Coupe', 'Coupe'), ('EV', 'Electric Vehicle (EV)'), ('Convertible', 'Convertible'), ('Wagon', 'Wagon / Hatchback')], default='Sedan', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending Sale'), ('sold', 'Sold')], db_index=True, default='available', max_length=20)),
                ('mileage', models.PositiveIntegerField(help_text='Odometer in miles')),
                ('price', models.DecimalField(decimal_places=2, help_text='Sale price in USD', max_digits=10)),
                ('fuel_type', models.CharField(choices=[('Gasoline', 'Gasoline'), ('Electric', 'Electric (BEV)'), ('Hybrid', 'Hybrid / PHEV'), ('Diesel', 'Diesel')], default='Gasoline', max_length=20)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual (6-Speed/7-Speed)'), ('Dual-Clutch', 'Dual-Clutch (PDK/DCT)'), ('Single-Speed', 'Single-Speed (EV Direct)')], default='Automatic', max_length=20)),
                ('drivetrain', models.CharField(choices=[('AWD', 'All-Wheel Drive (AWD)'), ('RWD', 'Rear-Wheel Drive (RWD)'), ('FWD', 'Front-Wheel Drive (FWD)'), ('4WD', 'Four-Wheel Drive (4x4)')], default='AWD', max_length=20)),
                ('exterior_color', models.CharField(blank=True, default='Stealth Gray', max_length=50)),
                ('interior_color', models.CharField(blank=True, default='Obsidian Black Leather', max_length=50)),
                ('engine', models.CharField(blank=True, default='3.0L Twin-Turbo Inline-6', max_length=100)),
                ('horsepower', models.PositiveIntegerField(blank=True, help_text='Brake Horsepower (HP)', null=True)),
                ('primary_image_url', models.URLField(blank=True, default='', help_text='Direct URL for high-res vehicle photo (e.g. Unsplash automotive CDN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='Comma-separated highlights (e.g. Sport Chrono, Carbon Ceramic Brakes, Apple CarPlay)')),
                ('featured', models.BooleanField(default=False, help_text='Show in Showroom Highlights')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/gallery/')),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='inventory.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Gallery Image',
                'verbose_name_plural': 'Vehicle Gallery Images',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
