# Generated by Django 5.1.15 on 2026-09-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='exterior_color',
            field=models.CharField(blank=True, default='Stealth Gray', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='interior_color',
            field=models.CharField(blank=True, default='Obsidian Black Leather', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='primary_image_url',
            field=models.URLField(blank=True, default='', help_text='Direct URL for high-res vehicle photo (e.g. Unsplash automotive CDN)', max_length=500),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
