# Generated by Django 5.1.15 on 2026-09-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_vehicle_exterior_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='mileage',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odometer',
            field=models.PositiveIntegerField(default=0, help_text='Odometer reading in kilometers', verbose_name='Odometer (km)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='drivetrain',
            field=models.CharField(choices=[('FWD', 'Front-Wheel Drive (FWD)'), ('RWD', 'Rear-Wheel Drive (RWD)'), ('AWD', 'All-Wheel Drive (AWD)'), ('4WD', 'Four-Wheel Drive (4x4)')], default='FWD', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine',
            field=models.CharField(blank=True, default='1.5L Turbocharged Petrol', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='exterior_color',
            field=models.CharField(blank=True, default='Pearl Arctic White', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Gasoline', 'Petrol / Gasoline'), ('Diesel', 'Diesel (CRDi/TDI)'), ('Electric', 'Electric (BEV)'), ('Hybrid', 'Strong Hybrid / Mild Hybrid'), ('CNG', 'Bi-Fuel CNG')], default='Gasoline', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='horsepower',
            field=models.PositiveIntegerField(blank=True, help_text='Brake Horsepower (BHP / PS)', null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='interior_color',
            field=models.CharField(blank=True, default='Dual-Tone Ebony & Ivory Leatherette', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Ex-showroom / sale price in INR (₹)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic (Torque Converter / CVT)'), ('Manual', 'Manual (5-Speed / 6-Speed)'), ('Dual-Clutch', 'Dual-Clutch (DCT / DSG)'), ('Single-Speed', 'Single-Speed (EV Direct Drive)')], default='Automatic', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='trim',
            field=models.CharField(blank=True, help_text='e.g. Alpha, ZX, AX7 L, M Sport, SX(O)', max_length=64),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('SUV', 'SUV / Compact SUV'), ('Luxury', 'Premium / Luxury'), ('EV', 'Electric Vehicle (EV)'), ('Coupe', 'Coupe / Sports'), ('Truck', 'Truck / Pickup'), ('Convertible', 'Convertible'), ('Wagon', 'Wagon / Estate')], default='Sedan', max_length=20),
        ),
    ]
